package com.unik.salonee.models

data class BookingHistoryModel(
    val service_provider_id: String,
    val name: String,
    val business_name: String,
    val email: String,
    val country_code: String,
    val country_id: String,
    val city_id: String,
    val mobile: String,
    val password: String,
    val image: String,
    val business_licence: String,
    val is_approved: String,
    val is_email_verified: String,
    val city: String,
    val address: String,
    val referer_by: String,
    val membership_expiry: String,
    val latitude: String,
    val longitude: String,
    val created_time: String,
    val user_type: String,
    val modified_time: String,
    val status: String,
    val remark: String,
    val service_name: String,
    val service_provider_service_id: String,
    val service_image: String,
    val total_amount: String,
    val slot_date: String,
    val slot_id: String
)
